fonts:
  - https://fonts.googleapis.com/css?family=Roboto+Condensed:400,400i,700,700i&amp;subset=cyrillic
  - https://fonts.googleapis.com/css?family=Roboto:400,400i,700,700i&amp;subset=cyrillic
  - https://fonts.googleapis.com/css?family=Fira+Mono:400,700&amp;subset=cyrillic
  - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css

styles:
  - https://cdn.jsdelivr.net/npm/bulma/css/bulma.min.css
  - https://cdn-storage.github.io/styles/theme/theme.css

scripts:
  - https://cdn.jsdelivr.net/npm/jquery
  - https://cdn-storage.github.io/scripts/bulma/bulma.min.js
  - https://cdn-storage.github.io/scripts/theme/theme.min.js

meta:
  title: "Digital Resistance"
  keywords: ""
  copyright: ""
  theme-color: "#f3f6f9"

html:
  copyright: ""

cdn:
  url: "https://cdn-storage.github.io"

info:
  url: ""

discord:
  id: ""
  url: ""
