title: "Digital Resistance"
description: ""
lang: "ru_RU"
logo: ""
image: ""

sass:
  style: compressed
  sass_dir: assets/css/

twitter:
  username: ""
  card: ""

social:
  name: ""
  links:
  - https://twitter.com/
  - https://vk.com/

author:
  name: ""
  email: ""
  github: ""
  twitter: ""

plugins:
- jekyll-seo-tag
- jekyll-sitemap
